#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     ARM,           tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     DRIVE_LEFT,    tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     DRIVE_RIGHT,   tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C3_1,     INTAKE,        tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C3_2,     FLAG_RAISER,   tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C4_1,    HANG,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define DRIVE_JOY	joystick.joy1
#define DRIVE_JOY_LEFT joystick.joy1_y1
#define DRIVE_JOY_RIGHT joystick.joy1_y2
#define DRIVE_JOY_BUTTONS DRIVE_JOY_Buttons
#define DRIVE_JOY_PRESSED joy1Btn

#define OP_JOY joystick.joy2
#define OP_JOY_LEFT joystick.joy2_y1
#define OP_JOY_RIGHT joystick.joy2_y2
#define OP_JOY_BUTTONS joystick.joy2_Buttons
#define OP_JOY_PRESSED joy2Btn

#define JOY_POLL_DELAY 10
#define DRIVE_SET_DELAY 10
#define DEBUGGER writeDebugStreamLine
static const bool USE_LOG_SCALE=true;

#define FLAG_SPEED 100

#define SERVO_HANG_POSITION 255

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "initialize.h"

#include "common.h"
#include "events.h" //Order is important here. This must be included above poll_joystick
#include "poll_joystick.h"

//Auto definitions
#define DRIVE_SPEED 71
#define TURN_SPEED 100
#define ARM_SPEED 100
#define INTAKE_SPEED 100

#define TO_BUCKET_TIME 1000
#define DROP_ARM_TIME 1
#define RUN_INTAKE_TIME 1
#define BACKOUT_TIME 1
#define TURN_90_TIME 1
#define FORWARD_BEYOND_RAMP_TIME 1170
#define FORWARD_TO_RAMP_TIME 1
#define FORWARD_ONTO_RAMP_TIME 1

task main() {
	int time=0;
	_setDriveMotors(DRIVE_SPEED,DRIVE_SPEED);
	while(time <= TO_BUCKET_TIME)
	{
		time+=5;
		wait1Msec(5);
	}
	_setDriveMotors(0,0);
	_setArmMotor(-ARM_SPEED);
	time=0;
 	while(time <= DROP_ARM_TIME)
 	{
 		time+=5;
 		wait1Msec(5);
	}
	_setArmMotor(0);
	time=0;
	_setIntakeMotor(INTAKE_SPEED);
	while(time <= RUN_INTAKE_TIME)
	{
		time+=5;
		wait1Msec(5);
	}
	_setIntakeMotor(0);
	time=0;
	_setDriveMotors(-DRIVE_SPEED, -DRIVE_SPEED);
	while(time <= BACKOUT_TIME)
	{
		time+=5;
		wait1Msec(5);
	}
	_setDriveMotors(0,0);
	time=0;
	_setDriveMotors(TURN_SPEED,-TURN_SPEED);
	while(time <= TURN_90_TIME)
	{
		time+=5;
		wait1Msec(5);
	}
	_setDriveMotors(0,0);
	time=0;
	_setDriveMotors(DRIVE_SPEED, DRIVE_SPEED);
	while(time < FORWARD_BEYOND_RAMP_TIME)
	{
		time+=5;
		wait1Msec(5);
	}
	_setDriveMotors(0,0);
	time=0;
	_setDriveMotors(TURN_SPEED,-TURN_SPEED);
	while(time <= TURN_90_TIME)
	{
		time+=5;
		wait1Msec(5);
	}
	_setDriveMotors(0,0);
	time=0;
	_setDriveMotors(DRIVE_SPEED, DRIVE_SPEED);
	while(time <= FORWARD_TO_RAMP_TIME)
	{
		time+=5;
		wait1Msec(5);
	}
	_setDriveMotors(0,0);
	time=0;
	_setDriveMotors(TURN_SPEED,-TURN_SPEED);
	while(time <= TURN_90_TIME)
	{
		time+=5;
		wait1Msec(5);
	}
	_setDriveMotors(0,0);
	time=0;
	_setDriveMotors(DRIVE_SPEED, DRIVE_SPEED);
	while(time <= FORWARD_ONTO_RAMP_TIME)
	{
		time+=5;
		wait1Msec(5);
	}
	_setDriveMotors(0,0);
}
