#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     IRSENSOR,       sensorI2CCustom)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     ARM,           tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     DRIVE_LEFT,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     DRIVE_RIGHT,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     INTAKE,        tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C3_2,     FLAG_RAISER,   tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C4_1,    FLAP_SERVO,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define DRIVE_JOY	joystick.joy1
#define DRIVE_JOY_LEFT joystick.joy1_y1
#define DRIVE_JOY_RIGHT joystick.joy1_y2
#define DRIVE_JOY_BUTTONS DRIVE_JOY_Buttons
#define DRIVE_JOY_PRESSED joy1Btn

#define OP_JOY joystick.joy2
#define OP_JOY_LEFT joystick.joy2_y1
#define OP_JOY_RIGHT joystick.joy2_y2
#define OP_JOY_BUTTONS joystick.joy2_Buttons
#define OP_JOY_PRESSED joy2Btn

#define JOY_POLL_DELAY 10
#define DRIVE_SET_DELAY 10
#define DEBUGGER writeDebugStreamLine
static const bool USE_LOG_SCALE=true;

#define FLAG_SPEED -100

#define SERVO_HANG_POSITION 255

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "initialize.h"

#include "events.h" //Order is important here. This must be included above poll_joystick
#include "poll_joystick.h"
#include "auto_common.h"
#include "drivers/hitechnic-irseeker-v2.h"

//definitions
#define DRIVE_SPEED 40
#define TURN_SPEED 60
#define ARM_SPEED 100
#define INTAKE_SPEED -30

#define FORTY_FIVE_DEGREES 570
#define NINETY_DEGREES 1370

#define BUCK1_TICKS 375
#define BUCK2_TICKS 1700
#define BUCK3_TICKS 3750
#define BUCK4_TICKS 5200
#define BUCK_WINDOW_TICKS 40

#define ARM_TIME 2200
#define KICK_TIME 1000

#define END_OF_LINE 5300
#define INTERMEDIATE_TICKS 1000
#define ONTO_BRIDGE_TICKS 3000

#define IR_THRESHOLD 80

int foundVal = BUCK4_TICKS;
//function prototypes

task main () {
	//waitForStart();
	flapClosed();

	zeroEncoders();
	//while(DRIVE_ENCODERS < BUCK1_TICKS) {
	//	_setDriveMotors(DRIVE_SPEED, DRIVE_SPEED);
	//	wait1Msec(5);
	//}
	//moveDriveTicks(DRIVE_SPEED, DRIVE_ENCODERS+630);
	//stopDrive();

	//writeDebugStreamLine("foundVal %d", foundVal);

	//turnDriveRightTicks(TURN_SPEED, DRIVE_ENCODERS+NINETY_DEGREES+400);
	//runDriveTime(DRIVE_SPEED, 500);

	runArmTime(ARM_SPEED, ARM_TIME);
	runDriveTime(DRIVE_SPEED, 1000);
	wait1Msec(300);
	//runArmTime(-ARM_SPEED, 600);
	flapOpen();
	runIntakeTime(INTAKE_SPEED, KICK_TIME);
	flapClosed();
	//runArmTime(ARM_SPEED, 600);
	runDriveTime(-DRIVE_SPEED, 1000);
	runArmTime(-ARM_SPEED, ARM_TIME-200);

	turnTime(TURN_SPEED, 500);
	//turnDriveLeftTicks(TURN_SPEED, DRIVE_ENCODERS-(NINETY_DEGREES/2)-100);

	zeroEncoders();

	for (int i=4750; i>=0; i=i-5) {
		_setDriveMotors(DRIVE_SPEED, DRIVE_SPEED-5);
		_setIntakeMotor(100);
		wait1Msec(5);
	}

	stopDrive();
	_setIntakeMotor(0);
	flapClosed();

	for (int i=750; i>=0; i=i-5) {
		_setDriveMotors(-DRIVE_SPEED+5, -DRIVE_SPEED);
		wait1Msec(5);
	}

	turnTime(TURN_SPEED, 400);
	runDriveTime(-100, 2750);

}
