#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     HTIRS2,         sensorNone)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define HTIRS2setDSPMode setMode

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "drivers/hitechnic-irseeker-v2.h"


int sensorData[5];

task main()
{
	setMode(HTIRS2, 1200);
  while (true)
  {
  	writeDebugStream("curtime is %d",nPgmTime);
  	HTIRS2readAllDCStrength(HTIRS2, sensorData[0],sensorData[1],sensorData[2],sensorData[3],sensorData[4]);
  	writeDebugStream("DC: ");
  	for(int i=0; i<5; i++)
  	{
  	  writeDebugStream("%d ",sensorData[i]);
  	}
  	writeDebugStream("AC: ");
  	HTIRS2readAllACStrength(HTIRS2, sensorData[0],sensorData[1],sensorData[2],sensorData[3],sensorData[4]);
  	for(int i=0; i<5; i++)
  	{
  		writeDebugStream("%d ",sensorData[i]);
  	}
  	writeDebugStreamLine("%d ",nPgmTime);
  	wait1Msec(5);
  }
}
